#!/usr/bin/env ruby

# Convert a kitFORTH source program to a C file

member = ARGV[0]

abort "Usage: #$0 <member-name>" if member.nil?

$stdout << "// This file is auto-generated by fs-to-c.rb
// Do not edit!

char *#{member} ="

$stdin.each_line do |line|
  $stdout << "\n  \""
  $stdout << line.chomp.gsub("\\", "\\"*4).gsub("\"", "\\\"")
  $stdout << "\\n\""
end

$stdout << ";\n"
