#!/usr/bin/env ruby

# Convert a kitFORTH source program to a C file

member = ARGV[0]

abort "Usage: #$0 <member-name>" if member.nil?

$stdout << "// This file is auto-generated by fs-to-c.rb
// Do not edit!

char *#{member} = \""

$stdout << $stdin.read.split(/\s+/).join(' ').gsub('\\', '\\\\')
$stdout << "\";\n"
